### ISSUE TITLE
Custom model integretion with StyleRes.

### ISSUE THREAD

**Issue by waleedrazakhan92** [hamzapehlivan/StyleRes#7]
Great work! 
I'm using StylreRes model to get a latent vector which i then use in my pipeline to edit images. I was hoping to integrate my custom StyleGan checkpoint instead of Nvidia's. In the paper it's mentioned that a fixed StyleGan generator is used in the training phase. And after the first phase the missing features are added by the Styleres model. I want to integrate my custom checkpoint instead of the pretrained one as the data that I've trained my model on is cleaner and different with perfect face front images. 
How do i integrate my own model and should there be any changes required to accomplish it? Your guidance would be highly appreciated

**Comment by hamzapehlivan** [comment]
Hi sorry for the late response,

I would first try to replace the existing generator with the new one to see if it works. Because both generators are trained with face images, StyleRes might work automatically. 

If it does not work, I would retrain StyleRes with the new generator. Although training code is not available in the repo, I send it via email upon request.

All the best

**Comment by waleedrazakhan92** [comment]
@hamzapehlivan Thankyou for the response. I'll try the suggested solution.
